--- Mine an entire volume. This mining style inverts the DesiredBlocks filter and
--- interprets it as a block blacklist instead. Due to the primitive layer-by-layer
--- pattern that this style takes, if a blacklisted block is seen, the mining
--- task will be immediately canceled.
---
--- Task must start either within, or directly adjacent to the volume on one of
--- the turtle's faces.
--- @class FullVolumeMiner
--- @field name "full_volume_miner"
--- @field volume {corner_1: CoordPosition, corner_2: CoordPosition}