--- Mine in a volume, blindly depth-first mining incidental blocks within the
--- volume constraint until a desired block is found, which will then be recursively
--- mined out, before continuing the blind search.
---
--- Do note that while searching, the turtle cannot break blocks outside of the
--- requested volume, however the turtle _IS_ allowed to break blocks outside of
--- the volume when recursively mining a desired block. Thus, do NOT pass in
--- groups to search_mine with this mode selected that are non-restrictive enough
--- (ie, patterns that match anything).
---
--- The mining volume is expressed by two corners that form a rectangular prism,
--- and the order of the two points does not matter.
---
--- Task must start either within, or directly adjacent to the volume on one of
--- the turtle's faces.
--- @class SearchVolumeMiner
--- @field name "search_volume_miner"
--- @field volume {corner_1: CoordPosition, corner_2: CoordPosition}